config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :adoptions

  resources :customers
  get '/customers/:id/matches', action: :matches, controller: 'customers'
  post '/customers/:id/adopt', action: :adopt, controller: 'customers'

  resources :pets
  get '/pets/:id/matches', action: :matches, controller: 'pets'
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :id, numericality: { only_integer: true, greater_than: 0 }
  validates :name, length: { maximum: 70 }
  validates_datetime :available_from, allow_nil: true
  validates :age, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100}, allow_nil: true
  enum species: { cat: "cat", dog: "dog", rabbit: "rabbit" }
  enum breed: { labrador: "labrador", poodle: "poodle", spaniel: "spaniel", terrier: "terrier" }

  has_one :adoption
  has_one :customer, through: :adoption

  validate :validate_breed_association
  def validate_breed_association
    if species != "dog" && breed
        errors.add(:breed, :invalid)
    end
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /pets/1/matches
  # GET /pets/1/matches.json
  def matches
    @pet = Pet.find(params[:id])
    @matched_customers = []

    if !@pet.adoption
      customer_preferences = CustomerPreference.where(
        "species = '{}' OR '#{@pet.species}' = ANY (species)"
      )

      customer_preferences.each do |preference|
        next if (@pet.species == 'dog' && preference.breed.any? && preference.breed.exclude?(@pet.breed))
        next if (preference.age && !@pet.age)
        next if (preference.age == 'less than 2 years' && @pet.age >= 2)
        next if (preference.age == '2 to 4 years' && (@pet.age < 2 || @pet.age > 4))
        next if (preference.age == 'more than 4 years' && @pet.age <= 4)
        @matched_customers.push(preference.customer_id)
      end
    end

    respond_to do |format|
      format.html { render :matches, notice: 'Found matched customers.' }
      format.json { render json: @matched_customers, status: :ok, location: @pet }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:id, :name, :available_from, :age, :species, :breed)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<head>
  <%= javascript_pack_tag 'pet_vue' %>
</head>

<%= content_tag :div,
  id: "pet-form",
  data: {
    id: pet.id,
    pet: pet.to_json(except: [:created_at, :updated_at])
  } do %>

  <div class="container-fluid">

    <div class="form-group">
      <label>ID</label>
      <input class="form-control" id="pet_id" v-model="pet.id" placeholder="Enter Pet ID (Integer)">
    </div>

    <div class="form-group">
      <label>Name</label>
      <input class="form-control" id="name" v-model="pet.name" placeholder="Enter Pet Name">
    </div>

    <div class="form-group">
      <label>Available From</label>
      <input class="form-control" id="available_from" v-model="pet.available_from" placeholder="Enter Pet Name">
    </div>

    <div class="form-group">
      <label>Age</label>
      <input class="form-control" id="age" v-model="pet.age" placeholder="Enter Pet Age">
    </div>

    <div class="form-group">
      <label>Species</label>
      <select class="form-control" id="species" v-model="pet.species">
        <%= options_for_select([
          ['Unknown', nil],
          ['cat', 'cat'],
          ['dog', 'dog'],
          ['rabbit', 'rabbit']
        ]) %>
      </select>
    </div>

    <div class="form-group">
      <label>Breed</label>
      <select class="form-control" id="breed" v-model="pet.breed">
        <%= options_for_select([
          ['Unknown', nil],
          ['labrador', 'labrador'],
          ['poodle', 'poodle'],
          ['spaniel', 'spaniel'],
          ['terrier', 'terrier']
        ]) %>
      </select>
      <small id="breedHelp" class="form-text text-muted">Select breed only for a dog.</small>
    </div>

    <button v-on:click="save" class="btn-primary">Save</button>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h3>Editing Pet</h3>
<%= render 'form', pet: @pet %>

<br />
<%= button_to 'Back To Pet List', pets_path, :method => "get", class: 'btn-info' %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Available from</th>
      <th>Age</th>
      <th>Species</th>
      <th>Breed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.id %></td>
        <td><%= pet.name %></td>
        <td><%= pet.available_from %></td>
        <td><%= pet.age %></td>
        <td><%= pet.species %></td>
        <td><%= pet.breed %></td>
        <td><%= button_to 'Edit', edit_pet_path(pet), :method => "get", class: 'btn-primary' %></td>
        <td><%= button_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= button_to 'New Pet', new_pet_path, :method => "get", class: 'btn-primary' %>

app/views/pets/matches.html.erb
<div class="container-fluid">
  <h3>Pet <%= @pet.id %>: <%= @pet.name %></h3>
  <% if @pet.adoption %>
    <h4>Status: Adopted</h4>
  <% else %>
    <h4>Status: Available</h4>
    <h5>Matching Customers:</h5>
    <% @matched_customers.each do |match| %>
      <li><%= match %></li>
    <% end %>
  <% end %>
</div>

app/views/pets/new.html.erb
<h3>New Pet</h3>
<%= render 'form', pet: @pet %>

<br />
<%= button_to 'Back To Pet List', pets_path, :method => "get", class: 'btn-info' %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @pet.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Available from:</strong>
  <%= @pet.available_from %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Species:</strong>
  <%= @pet.species %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>